name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_HUB_REPOSITORY: yelloman/jap-your-name

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Build with Gradle Wrapper (Skip Tests)
        run: ./gradlew build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}:${{ github.sha }},${{ env.DOCKER_HUB_REPOSITORY }}:latest
          
      - name: Clean up old Docker images
        run: |
          # Docker Hub에 로그인 상태 확인
          docker info
          
          # centurylink/image-clean 이미지 pull 시도
          docker pull centurylink/image-clean:latest
          
          # 이미지 pull 성공 시 실행
          docker run --rm \
            -e DOCKER_HUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} \
            -e DOCKER_HUB_PASSWORD=${{ secrets.DOCKERHUB_TOKEN }} \
            centurylink/image-clean --repo ${{ env.DOCKER_HUB_REPOSITORY }} --keep 5

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
