name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_HUB_REPOSITORY: yelloman/jap-your-name

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Build with Gradle Wrapper (Skip Tests)
        run: ./gradlew build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}:${{ github.sha }},${{ env.DOCKER_HUB_REPOSITORY }}:latest
          
      - name: Clean up old Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          # 리포지토리의 모든 태그 가져오기
          TAGS=$(curl -s -H "Authorization: Bearer $(echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin >/dev/null && docker auth token)" \
            "https://hub.docker.com/v2/repositories/${{ env.DOCKER_HUB_REPOSITORY }}/tags/?page_size=10000" | jq -r '.results[].name')
          
          # 최신 5개 태그를 제외한 나머지 삭제
          echo "$TAGS" | sort -r | tail -n +6 | while read TAG; do
            curl -s -X DELETE \
              -H "Authorization: Bearer $(echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin >/dev/null && docker auth token)" \
              "https://hub.docker.com/v2/repositories/${{ env.DOCKER_HUB_REPOSITORY }}/tags/$TAG/"
            echo "Deleted tag: $TAG"
          done

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
